name: Build

on:
  push:
    branches: [ main ]
    tags: [ "*" ]
    paths-ignore: [ "README.md" ]

  pull_request:
    branches: [ main ]

jobs:
  build:

    name: Build Release version
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: adopt

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assembleDebug

    - name: List Output Release
      run: ls -al app/build/outputs/apk/debug

    - name: Upload the Release binary
      uses: actions/upload-artifact@v2
      with:
        name: NosoMobile-Release
        path: app/build/outputs/apk/debug/app-debug.apk

  package-release:
    if: contains(github.ref, '/tags/')

    name: Package and create GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Download the Release binary
      uses: actions/download-artifact@v2
      
    - name: List files
      run: ls -alF NosoMobile-Release

    - name: Create release files
      run: |
        cd NosoMobile-Release
        mv app-debug.apk NosoMobile-${{ steps.vars.outputs.tag }}.apk
        zip -r NosoMobile-${{ steps.vars.outputs.tag }}.zip NosoMobile-${{ steps.vars.outputs.tag }}.apk
    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        name: NosoMobile ${{ steps.vars.outputs.tag }}
        body_path: release-notes.md
        files: |
          NosoMobile-Release/*.apk
          NosoMobile-Release/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}